<?php
/**
 * Routing debugger template.
 *
 * @param string   $presenter
 * @param array    $params
 * @param string   $router
 * @param array    $routers
 */
?>
</pre></xmp>

<style type="text/css">
/* <![CDATA[ */

	#routingDebugger, #routingDebuggerButton {
		font: 90%/1.4 "Trebuchet MS", "Geneva CE", lucida, sans-serif;
		position: absolute;		
		left: 5px;
		top: 5px;
		z-index: 23179;
		margin: 0;
		padding: 10px;
		width: auto;
		color: black;
		background: #f6f6f6;
		border: 1px dotted gray;
		cursor: pointer;
		opacity: .97;
		=filter: alpha(opacity=97);
		visibility: hidden;
		float: none;
	}
	
	#routingDebuggerButton {
		font: normal normal 11px/1.4 Consolas, Arial;
		background: #eee;
		padding: 2px;
		cursor: pointer;
		opacity: .70;
		=filter: alpha(opacity=70);
		visibility: visible;
		float: left;
	}
	
	#routingDebuggerButton:hover {
		opacity: 1;
		=filter: none;
	}	
	
	#routingDebugger h1 {
		font-size: 140%;
		color: #165ca3;
		margin-top: 0;
		text-align: center;
	}

	#routingDebugger h2 {
		font-size: 120%;
		color: black;
	}

	#routingDebugger table {
		padding: 0;
		margin: 0;
		border-collapse: collapse;
	}

	#routingDebugger table td, #routingDebugger table th {
		color: #525b37;
		background: #fff;
		border: 1px solid #d1cdab;
		padding: 6px;
		text-align: left;
	}

	#routingDebugger table th {
		color: #165ca3;
		background: #e3e9ba;
		font-size: 90%;
	}

	#routingDebugger table .alt td {
		background: #f8f8f0;
	}

	#routingDebugger .may, #routingDebugger .yes {
		color: green;
	}

	#routingDebugger .yes {
		font-weight: bold;
	}

/* ]]> */
</style>

<div id="routingDebuggerButton">Routing debugger</div>
<div id="routingDebugger">
	<h1>Routing debugger</h1>
	
	<?php if (!empty($presenter)): ?>
		<h2>&#x25BA; <?php echo htmlSpecialChars($presenter . ':' . (isset($params[Presenter::ACTION_KEY]) ? $params[Presenter::ACTION_KEY] : Presenter::$defaultAction)) ?></h2>

		<?php if (empty($params)): ?>
			<p>No parameters.</p>

		<?php else: ?>
			<table>
			<thead>
			<tr>
				<th>Parameter</th>
				<th>Value</th>
			</tr>
			</thead>
			<tbody>
			<?php foreach ($params as $key => $value): ?>
			<tr>
				<td><code><?php echo htmlSpecialChars($key) ?></code></td>
				<td><code><?php echo htmlSpecialChars($value) ?></code></td>
			</tr>
			<?php endforeach ?>
			</tbody>
			</table>
		<?php endif ?>
	<?php endif ?>

	<!-- ~~~~~~~~~~~ -->

	<?php if (empty($router)): ?>
		<h2>&#x25BA; Not matched</h2>

	<?php else: ?>
		<h2>&#x25BA; Matched by <?php echo htmlSpecialChars($router) ?></h2>
	<?php endif ?>

	<!-- ~~~~~~~~~~~ -->

	<?php if (empty($routers)): ?>
		<p>No routes defined.</p>

	<?php else: ?>
		<table>
		<thead>
		<tr>
			<th>Matched?</th>
			<th>Class</th>
			<th>Mask</th>
			<th>Defaults</th>
		</tr>
		</thead>

		<tbody>
		<?php foreach ($routers as $router): ?>
		<tr>
			<td class="<?php echo $router['matched'] ?>"><?php echo $router['matched'] ?></td>
			<td><code><?php echo htmlSpecialChars($router['class']) ?></code></td>
			<td><code><strong><?php echo htmlSpecialChars($router['mask']) ?></strong></code></td>
			<td><code>
			<?php foreach ($router['defaults'] as $key => $value): ?>
				<?php echo htmlSpecialChars($key), " = ", $value === NULL ? '<i>NULL</i>' : htmlSpecialChars($value) ?><br>
			<?php endforeach ?>
			</code></td>
		</tr>
		<?php endforeach ?>
		</tbody>
		</table>
	<?php endif ?>
</div>


<script type="text/javascript">
/* <![CDATA[ */
document.getElementById('routingDebugger').onclick = function(e) {
	this.style.visibility = 'hidden';
	document.getElementById('routingDebuggerButton').style.visibility = 'visible';
}


document.getElementById('routingDebuggerButton').onclick = function(e) {
	this.style.visibility = 'hidden';
	document.getElementById('routingDebugger').style.visibility = 'visible';
}

/* ]]> */
</script>